name: 'Comment Action'
description: 'Post the link to the temp storybook url'
author: 'Dan Drory'

inputs:
  GITHUB_TOKEN:
    description: 'GitHub token'
    required: true
  BUCKET_NAME:
    description: 'Bucket name'
    required: true
  BUILD_VERSION:
    description: 'Version'
    required: false

runs:
  using: 'node16'
  main: '../../../../scripts/comment.js'