<template>
  <svg
    width="31"
    height="30"
    viewBox="0 0 31 30"
    fill="none"
    xmlns="http://www.w3.org/2000/svg"
  >
    <rect
      x="3.69983"
      y="7"
      width="23"
      height="16"
      rx="2"
      stroke="currentColor"
    />
    <rect
      x="19.6998"
      y="17"
      width="3"
      height="2"
      rx="0.5"
      stroke="currentColor"
    />
    <rect
      x="3.69983"
      y="10"
      width="23"
      height="3"
      fill="currentColor"
      stroke="currentColor"
    />
  </svg>
</template>
