import P2AutoComplete from './InputAutoComplete.vue';

export default {
  title: 'V2/Atoms/Forms/InputAutoComplete',
  component: P2AutoComplete,
  argTypes: {},
  args: {
    reduceValue: false,
  },
};

const Template = (args, { argTypes }) => ({
  components: { P2AutoComplete },
  props: Object.keys(argTypes),
  template: `
    <div>
      <P2AutoComplete v-model="selected" v-bind="$props" @selectedObj="selectedOption">
        <template #list-footer>I am a Footer</template>
      </P2AutoComplete>
      <br />
      Selected option: {{ selected }}
    </div>
  `,
  data() {
    return {
      selected: null,
    };
  },
  methods: {
    selectedOption(selectedOption) {
      this.$data.selected = selectedOption;
    },
  },
});

export const Default = Template.bind({});
Default.args = {
  initInput: '',
  disabled: true,
  disableFilter: true,
  noDropOnStart: true,
};

export const Placeholder = Template.bind({});
Placeholder.args = {
  placeHolder: 'Search for your property',
  initInput: '',
  disabled: true,
  disableFilter: true,
  noDropOnStart: true,
};

export const LongPlaceholder = Template.bind({});
LongPlaceholder.args = {
  placeHolder:
    'Search for your property, Search for your property, Search for your property, Search for your property',
  initInput: '',
  disabled: true,
  disableFilter: true,
  noDropOnStart: true,
};

export const Loading = Template.bind({});
Loading.args = {
  loading: true,
  initInput: '',
  disabled: true,
  disableFilter: true,
  noDropOnStart: true,
};

export const DropDown = Template.bind({});
DropDown.args = {
  optionLabelVar: 'label',
  customLabelVar: 'label',
  reduceValue: false,
  initInput: '001',
  selectedBy: 'id',
  optionItems: [
    {
      id: '001',
      label: 'Apple',
    },
    {
      id: '002',
      label: 'Orange',
    },
    {
      id: '003',
      label: 'Eggplant',
    },
    {
      id: '004',
      label: 'Banana',
    },
    {
      id: '005',
      label: 'Watermelon',
    },
  ],
};

export const DropDownWithFooter = Template.bind({});
DropDownWithFooter.args = {
  optionLabelVar: 'label',
  customLabelVar: 'label',
  initInput: '001',
  selectedBy: 'id',
  showFooter: true,
  addFooter: true,
  noOptionsText: 'No selection found',
  footerContent: 'This is a footer',
  //template: '<div><P2AutoComplete v-model="selected" @selectedObj="selectedOption" v-bind="$props"><template #list-footer> I am a Footer </template></P2AutoComplete>selected option:{{$data.selected}}</div>',
  optionItems: [
    {
      id: '001',
      label: 'Apple',
    },
    {
      id: '002',
      label: 'Orange',
    },
    {
      id: '003',
      label: 'Eggplant',
    },
    {
      id: '004',
      label: 'Banana',
    },
    {
      id: '005',
      label: 'Watermelon',
    },
    {
      id: '006',
      label: 'Pear',
    },
    {
      id: '007',
      label: 'Peach',
    },
    {
      id: '008',
      label: 'Raspberry',
    },
    {
      id: '009',
      label: 'Strawberry',
    },
    {
      id: '010',
      label: 'Lychee',
    },
  ],
};

export const OptionPrefixIcon = Template.bind({});
OptionPrefixIcon.args = {
  customLabelVar: 'label',
  initInput: '001',
  selectedBy: 'id',
  allowOptionIcon: true,
  prefixIcon: 'house',
  optionItems: [
    {
      id: '001',
      label: '<span class="af_hl">highlight</span> test1',
      icon: 'house',
    },
    {
      id: '002',
      label: '<span class="af_hl">highlight</span> test2',
      icon: 'Apartment',
    },
  ],
};

export const LongOptionLabel = Template.bind({});
LongOptionLabel.args = {
  customLabelVar: 'label',
  initInput: '001',
  selectedBy: 'id',
  allowOptionIcon: true,
  prefixIcon: 'house',
  optionItems: [
    {
      id: '001',
      label:
        'this is a long option label and will render with more text thus an elipsis will be created!',
      icon: 'house',
    },
    {
      id: '002',
      label: '<span class="af_hl">highlight</span> test2',
      icon: 'circle',
    },
  ],
};

export const InputPrefixIcon = Template.bind({});
InputPrefixIcon.args = {
  loading: true,
  allowOptionIcon: true,
  hideOpenIndicator: true,
  hideInputOnSelected: true,
  hideClearBtn: false,
  noDropOnStart: true,
  showSelectedIcon: true,
  placeHolder: 'Search for your property',
  text: 'Search for your <b>property</b>',
  prefixIcon: 'house',
  footer: "Can't find your address? <a href='#'>Enter it manually</a>",
  disableFilter: true,
  optionItems: [
    {
      code: '001',
      label: '1 An bar Mews, HALLAM VIC 3803',
      custom_label:
        '<span class="af_hl">1</span> <span class="af_hl">An</span>bar Mews, HALLAM VIC 3803',
      icon: 'house',
    },
    {
      code: '002',
      label: '3 An bar Mews, HALLAM VIC 3803',
      custom_label:
        '<span class="af_hl">3</span> <span class="af_hl">An</span>bar Mews, HALLAM VIC 3803',
      icon: 'house',
    },
    {
      code: '003',
      label: '5 An bar Mews, HALLAM VIC 3803',
      custom_label:
        '<span class="af_hl">5</span> <span class="af_hl">An</span>bar Mews, HALLAM VIC 3803',
      icon: 'house',
    },
    {
      code: '004',
      label: '7 An bar Mews, HALLAM VIC 3803',
      custom_label:
        '<span class="af_hl">7</span> <span class="af_hl">An</span>bar Mews, HALLAM VIC 3803',
      icon: 'house',
    },
    {
      code: '005',
      label: '9 An bar Mews, HALLAM VIC 3803',
      custom_label:
        '<span class="af_hl">9</span> <span class="af_hl">An</span>bar Mews, HALLAM VIC 3803',
      icon: 'house',
    },
    {
      code: '006',
      label: '11 An bar Mews, HALLAM VIC 3803',
      custom_label:
        '<span class="af_hl">11</span> <span class="af_hl">An</span>bar Mews, HALLAM VIC 3803',
      icon: 'house',
    },
    {
      code: '007',
      label: '13 An bar Mews, HALLAM VIC 3803',
      custom_label:
        '<span class="af_hl">13</span> <span class="af_hl">24</span> Station Street, WEST RYDE NSW 2114',
      icon: 'house',
    },
    {
      code: '008',
      label: '15 An bar Mews, HALLAM VIC 3803',
      custom_label:
        '<span class="af_hl">15</span> <span class="af_hl">26</span> Station Street, WEST RYDE NSW 2114',
      icon: 'house',
    },
  ],
};

export const InstitutionList = Template.bind({});
InstitutionList.args = {
  initInput: '',
  optionLabelVar: 'name',
  selectedOptionLabelVar: 'name',
  selectedOptionAllowOptionIcon: true,
  optionAllowOptionIcon: true,
  optionIconFamily: 'fas',
  optionIconClasses: 'fa-xs',
  selectedBy: 'name',
  allowOptionIcon: true,
  prefixIcon: '',
  optionItems: [
    {
      slug: 'adcu',
      name: 'Australian Military Bank',
      credentials: [
        {
          name: 'Member Number',
          fieldID: 'username',
          type: 'TEXT',
          description: '',
          values: '',
          validation: {
            minLength: 0,
            maxLength: 9999999,
            chars: '*',
          },
        },
        {
          name: 'Access Code',
          fieldID: 'password',
          type: 'password',
          description: '',
          values: '',
          validation: {
            minLength: 0,
            maxLength: 9999999,
            chars: '*',
          },
        },
      ],
      status: '',
      severity: '0',
      present: '1',
      available: '1',
      searchable: '1',
      display: '0',
      searchVal: 'australianmilitarybankambaustraliandefencecreditunionadcu',
      region: 'au',
      export_with_password: '0',
      estatements_supported: '1',
      transaction_listings_supported: '1',
      card_validation_supported: '0',
      requires_preload: '0',
      requires_mfa: '0',
      is_business_bank: '0',
      ocr_supported: '0',
      type: 'bank',
      do_not_proxy: '0',
      updated_at: '2023-08-01 10:27:53',
      max_days: '180',
      get_address_supported: '0',
      supports_payment_summaries: '0',
      is_supported: '1',
      hide_merged_estatement_privacy_note: '0',
      time_next_stats_cron: '1690858807',
      time_next_session_cron: '1690858088',
      time_success_rate_updated: '1690851801',
      current_success_rate_ignore_abandoned: '0',
      current_success_rate_ignore_failed_login: '0',
      current_success_rate_all: '0',
      sessions_per_week: '1',
      time_next_outages_cron: '1690890018',
      icon: 'circle',
      iconColor: '#4caf50 !important',
    },
    {
      slug: 'adelaide',
      name: 'Adelaide Bank',
      credentials: [
        {
          name: 'Customer Number',
          fieldID: 'username',
          type: 'TEXT',
          description: '',
          values: '',
          validation: {
            minLength: 0,
            maxLength: 9999999,
            chars: '*',
          },
        },
        {
          name: 'Password',
          fieldID: 'password',
          type: 'password',
          description: '',
          values: '',
          validation: {
            minLength: 0,
            maxLength: 9999999,
            chars: '*',
          },
        },
      ],
      status: '',
      severity: '0',
      present: '1',
      available: '1',
      searchable: '1',
      display: '0',
      searchVal: 'adelaidebankbendigo',
      region: 'au',
      export_with_password: '0',
      estatements_supported: '1',
      transaction_listings_supported: '1',
      card_validation_supported: '0',
      requires_preload: '0',
      requires_mfa: '0',
      is_business_bank: '0',
      ocr_supported: '0',
      type: 'bank',
      do_not_proxy: '0',
      updated_at: '2023-08-01 10:27:54',
      max_days: '365',
      get_address_supported: '0',
      supports_payment_summaries: '0',
      is_supported: '1',
      hide_merged_estatement_privacy_note: '0',
      time_next_stats_cron: '1690858807',
      time_next_session_cron: '1690856984',
      time_success_rate_updated: '1690851796',
      current_success_rate_ignore_abandoned: '0',
      current_success_rate_ignore_failed_login: '0',
      current_success_rate_all: '0',
      sessions_per_week: '1',
      time_next_outages_cron: '1690889254',
      icon: 'circle',
      iconColor: '#4caf50 !important',
    },
    {
      slug: 'advantedge',
      name: 'Advantedge',
      credentials: [
        {
          name: 'Loan ID',
          fieldID: 'username',
          type: 'TEXT',
          description: '',
          values: '',
          validation: {
            minLength: 0,
            maxLength: 9999999,
            chars: '*',
          },
          keyboardType: 'default',
        },
        {
          name: 'Password',
          fieldID: 'password',
          type: 'password',
          description: '',
          values: '',
          validation: {
            minLength: 0,
            maxLength: 9999999,
            chars: '*',
          },
          keyboardType: 'default',
        },
      ],
      status: '',
      severity: '0',
      present: '1',
      available: '1',
      searchable: '1',
      display: '0',
      searchVal: 'advantedge',
      region: 'au',
      export_with_password: '0',
      estatements_supported: '1',
      transaction_listings_supported: '0',
      card_validation_supported: '0',
      requires_preload: '0',
      requires_mfa: '0',
      is_business_bank: '0',
      ocr_supported: '0',
      type: 'bank',
      do_not_proxy: '0',
      updated_at: '2023-08-01 10:27:54',
      max_days: '365',
      get_address_supported: '0',
      supports_payment_summaries: '0',
      is_supported: '1',
      hide_merged_estatement_privacy_note: '0',
      time_next_stats_cron: '1690858807',
      time_next_session_cron: '1690856634',
      time_success_rate_updated: '1690851785',
      current_success_rate_ignore_abandoned: '0',
      current_success_rate_ignore_failed_login: '0',
      current_success_rate_all: '0',
      sessions_per_week: '0',
      time_next_outages_cron: '1690891859',
      icon: 'circle',
      iconColor: '#4caf50 !important',
    },
    {
      slug: 'afterpay',
      name: 'Afterpay',
      credentials: [
        {
          name: 'Email address',
          fieldID: 'username',
          type: 'TEXT',
          description: '',
          values: '',
          validation: {
            minLength: 0,
            maxLength: 9999999,
            chars: '*',
          },
          keyboardType: 'email',
        },
        {
          name: 'Password',
          fieldID: 'password',
          type: 'password',
          description: '',
          values: '',
          validation: {
            minLength: 0,
            maxLength: 9999999,
            chars: '*',
          },
          keyboardType: 'default',
        },
      ],
      status: '',
      severity: '0',
      present: '1',
      available: '1',
      searchable: '1',
      display: '0',
      searchVal: 'afterpay',
      region: 'au',
      export_with_password: '0',
      estatements_supported: '0',
      transaction_listings_supported: '0',
      card_validation_supported: '0',
      requires_preload: '0',
      requires_mfa: '0',
      is_business_bank: '0',
      ocr_supported: '0',
      type: 'bank',
      do_not_proxy: '0',
      updated_at: '2023-08-01 10:27:55',
      max_days: '365',
      get_address_supported: '0',
      supports_payment_summaries: '0',
      is_supported: '1',
      hide_merged_estatement_privacy_note: '0',
      time_next_stats_cron: '1690858807',
      time_next_session_cron: '1690856636',
      time_success_rate_updated: '1690851795',
      current_success_rate_ignore_abandoned: '0',
      current_success_rate_ignore_failed_login: '0',
      current_success_rate_all: '0',
      sessions_per_week: '0',
      time_next_outages_cron: '1690889939',
      icon: 'circle',
      iconColor: '#4caf50 !important',
    },
    {
      slug: 'amex',
      name: 'American Express',
      credentials: [
        {
          name: 'User ID',
          fieldID: 'username',
          type: 'TEXT',
          description: '',
          values: '',
          validation: {
            minLength: 0,
            maxLength: 9999999,
            chars: '*',
          },
          keyboardType: 'default',
        },
        {
          name: 'Password',
          fieldID: 'password',
          type: 'password',
          description: '',
          values: '',
          validation: {
            minLength: 0,
            maxLength: 9999999,
            chars: '*',
          },
          keyboardType: 'default',
        },
      ],
      status: '',
      severity: '0',
      present: '0',
      available: '1',
      searchable: '1',
      display: '0',
      searchVal: 'amexamericanexpress',
      region: 'au',
      export_with_password: '0',
      estatements_supported: '1',
      transaction_listings_supported: '1',
      card_validation_supported: '1',
      requires_preload: '0',
      requires_mfa: '0',
      is_business_bank: '0',
      ocr_supported: '0',
      type: 'bank',
      do_not_proxy: '0',
      updated_at: '2023-08-01 10:27:54',
      max_days: '365',
      get_address_supported: '0',
      supports_payment_summaries: '0',
      is_supported: '1',
      hide_merged_estatement_privacy_note: '0',
      time_next_stats_cron: '1690858807',
      time_next_session_cron: '1690857100',
      time_success_rate_updated: '1690851791',
      current_success_rate_ignore_abandoned: '0',
      current_success_rate_ignore_failed_login: '0',
      current_success_rate_all: '0',
      sessions_per_week: '6',
      time_next_outages_cron: '1690890285',
      icon: 'circle',
      iconColor: '#4caf50 !important',
    },
    {
      slug: 'amp',
      name: 'AMP',
      credentials: [
        {
          name: 'My AMP Username',
          fieldID: 'username',
          type: 'TEXT',
          description: '',
          values: '',
          validation: {
            minLength: 0,
            maxLength: 9999999,
            chars: '*',
          },
          keyboardType: 'default',
        },
        {
          name: 'My AMP Password',
          fieldID: 'password',
          type: 'password',
          description: '',
          values: '',
          validation: {
            minLength: 0,
            maxLength: 9999999,
            chars: '*',
          },
          keyboardType: 'default',
        },
      ],
      status: '',
      severity: '0',
      present: '1',
      available: '1',
      searchable: '1',
      display: '0',
      searchVal: 'amplimited',
      region: 'au',
      export_with_password: '0',
      estatements_supported: '1',
      transaction_listings_supported: '1',
      card_validation_supported: '0',
      requires_preload: '0',
      requires_mfa: '0',
      is_business_bank: '0',
      ocr_supported: '0',
      type: 'bank',
      do_not_proxy: '0',
      updated_at: '2023-08-01 10:27:53',
      max_days: '365',
      get_address_supported: '0',
      supports_payment_summaries: '0',
      is_supported: '1',
      hide_merged_estatement_privacy_note: '0',
      time_next_stats_cron: '1690858807',
      time_next_session_cron: '1690858009',
      time_success_rate_updated: '1690851796',
      current_success_rate_ignore_abandoned: '0',
      current_success_rate_ignore_failed_login: '0',
      current_success_rate_all: '0',
      sessions_per_week: '6',
      time_next_outages_cron: '1690886451',
      icon: 'circle',
      iconColor: '#4caf50 !important',
    },
    {
      slug: 'anz',
      name: 'ANZ',
      credentials: [
        {
          name: 'Customer Registration Number',
          fieldID: 'username',
          type: 'TEXT',
          description: '',
          values: '',
          validation: {
            minLength: 9,
            maxLength: 20,
            chars: '0-9',
          },
          keyboardType: 'number',
        },
        {
          name: 'Password',
          fieldID: 'password',
          type: 'password',
          description: '',
          values: '',
          validation: {
            minLength: 8,
            maxLength: 16,
            chars: '*',
          },
          keyboardType: 'default',
        },
      ],
      status: '',
      severity: '2',
      present: '1',
      available: '1',
      searchable: '1',
      display: '1',
      searchVal: 'anzaustralianewzealandaustraliaandnewzealandbankinggroup',
      region: 'au',
      export_with_password: '0',
      estatements_supported: '1',
      transaction_listings_supported: '1',
      card_validation_supported: '0',
      requires_preload: '0',
      requires_mfa: '0',
      is_business_bank: '0',
      ocr_supported: '1',
      type: 'bank',
      do_not_proxy: '0',
      updated_at: '2023-08-01 10:27:53',
      max_days: '365',
      get_address_supported: '1',
      supports_payment_summaries: '0',
      is_supported: '1',
      hide_merged_estatement_privacy_note: '0',
      time_next_stats_cron: '1690858807',
      time_next_session_cron: '1690857757',
      time_success_rate_updated: '1690851803',
      current_success_rate_ignore_abandoned: '0',
      current_success_rate_ignore_failed_login: '0',
      current_success_rate_all: '0',
      sessions_per_week: '145',
      time_next_outages_cron: '1690888243',
      icon: 'circle',
      iconColor: '#4caf50 !important',
    },
    {
      slug: 'ausmutual',
      name: 'Australian Mutual Bank',
      credentials: [
        {
          name: 'Member Number',
          fieldID: 'username',
          type: 'TEXT',
          description: '',
          values: '',
          validation: {
            minLength: 0,
            maxLength: 9999999,
            chars: '*',
          },
        },
        {
          name: 'Access Code',
          fieldID: 'password',
          type: 'password',
          description: '',
          values: '',
          validation: {
            minLength: 0,
            maxLength: 9999999,
            chars: '*',
          },
        },
        {
          name: 'Date of Birth (DD MM YYYY)',
          fieldID: 'dob',
          type: 'pinpad',
          description: '',
          values: '',
          validation: {
            minLength: 0,
            maxLength: 9999999,
            chars: '*',
          },
        },
      ],
      status: '',
      severity: '0',
      present: '1',
      available: '1',
      searchable: '1',
      display: '1',
      searchVal:
        'sydneymutualbanksmbsydneycreditunionscuausmutualaustralianmutualsecuritycreditunionscuencompasscuencompasscreditunionencompasstransportcreditunionendeavourbankselectmutualbankingselectcreditunionendeavourmutualbank',
      region: 'au',
      export_with_password: '0',
      estatements_supported: '0',
      transaction_listings_supported: '0',
      card_validation_supported: '0',
      requires_preload: '1',
      requires_mfa: '0',
      is_business_bank: '0',
      ocr_supported: '0',
      type: 'bank',
      do_not_proxy: '0',
      updated_at: '2023-08-01 10:27:54',
      max_days: '365',
      get_address_supported: '0',
      supports_payment_summaries: '0',
      is_supported: '1',
      hide_merged_estatement_privacy_note: '0',
      time_next_stats_cron: '1690858807',
      time_next_session_cron: '1690858388',
      time_success_rate_updated: '1690851801',
      current_success_rate_ignore_abandoned: '0',
      current_success_rate_ignore_failed_login: '0',
      current_success_rate_all: '0',
      sessions_per_week: '0',
      time_next_outages_cron: '1690891001',
      icon: 'circle',
      iconColor: '#4caf50 !important',
    },
    {
      slug: 'aussieactivate',
      name: 'Aussie Activate',
      credentials: [
        {
          name: 'Access Number',
          fieldID: 'username',
          type: 'TEXT',
          description: '',
          values: '',
          validation: {
            minLength: 0,
            maxLength: 7,
            chars: '*',
          },
          keyboardType: 'default',
        },
        {
          name: 'Password',
          fieldID: 'password',
          type: 'password',
          description: '',
          values: '',
          validation: {
            minLength: 0,
            maxLength: 6,
            chars: '*',
          },
          keyboardType: 'default',
        },
      ],
      status:
        'We are currently experiencing issues in retrieving data from this institution. If you experience any problems, please try again later.',
      severity: '0',
      present: '0',
      available: '1',
      searchable: '1',
      display: '0',
      searchVal: 'aussieactivate',
      region: 'au',
      export_with_password: '0',
      estatements_supported: '0',
      transaction_listings_supported: '1',
      card_validation_supported: '0',
      requires_preload: '0',
      requires_mfa: '0',
      is_business_bank: '0',
      ocr_supported: '0',
      type: 'bank',
      do_not_proxy: '0',
      updated_at: '2023-08-01 10:27:54',
      max_days: '365',
      get_address_supported: '0',
      supports_payment_summaries: '0',
      is_supported: '1',
      hide_merged_estatement_privacy_note: '0',
      time_next_stats_cron: '1690858807',
      time_next_session_cron: '1690856722',
      time_success_rate_updated: '1690851787',
      current_success_rate_ignore_abandoned: '0',
      current_success_rate_ignore_failed_login: '0',
      current_success_rate_all: '0',
      sessions_per_week: '0',
      time_next_outages_cron: '1690891515',
      icon: 'circle',
      iconColor: '#fb8c00 !important',
    },
    {
      slug: 'aussieelevate',
      name: 'Aussie Elevate',
      credentials: [
        {
          name: 'Customer Number',
          fieldID: 'username',
          type: 'TEXT',
          description: '',
          values: '',
          validation: {
            minLength: 0,
            maxLength: 20,
            chars: '*',
          },
        },
        {
          name: 'Password',
          fieldID: 'password',
          type: 'password',
          description: '',
          values: '',
          validation: {
            minLength: 0,
            maxLength: 20,
            chars: '*',
          },
        },
      ],
      status: '',
      severity: '0',
      present: '1',
      available: '1',
      searchable: '1',
      display: '0',
      searchVal: 'aussieelevate',
      region: 'au',
      export_with_password: '0',
      estatements_supported: '1',
      transaction_listings_supported: '1',
      card_validation_supported: '0',
      requires_preload: '0',
      requires_mfa: '0',
      is_business_bank: '0',
      ocr_supported: '0',
      type: 'bank',
      do_not_proxy: '0',
      updated_at: '2023-08-01 10:27:54',
      max_days: '180',
      get_address_supported: '0',
      supports_payment_summaries: '0',
      is_supported: '1',
      hide_merged_estatement_privacy_note: '0',
      time_next_stats_cron: '1690876808',
      time_next_session_cron: '1690857221',
      time_success_rate_updated: '1690851799',
      current_success_rate_ignore_abandoned: '0',
      current_success_rate_ignore_failed_login: '0',
      current_success_rate_all: '0',
      sessions_per_week: '0',
      time_next_outages_cron: '1690887475',
      icon: 'circle',
      iconColor: '#4caf50 !important',
    },
    {
      slug: 'aussieiq',
      name: 'Aussie IQ / Home Loans',
      credentials: [
        {
          name: 'Access Code',
          fieldID: 'username',
          type: 'TEXT',
          description: '',
          values: '',
          validation: {
            minLength: 0,
            maxLength: 9999999,
            chars: '*',
          },
          keyboardType: 'default',
        },
        {
          name: 'Password',
          fieldID: 'password',
          type: 'password',
          description: '',
          values: '',
          validation: {
            minLength: 0,
            maxLength: 9999999,
            chars: '*',
          },
          keyboardType: 'default',
        },
      ],
      status: '',
      severity: '0',
      present: '1',
      available: '1',
      searchable: '1',
      display: '0',
      searchVal: 'aussieiqaussiehomeloans',
      region: 'au',
      export_with_password: '0',
      estatements_supported: '1',
      transaction_listings_supported: '1',
      card_validation_supported: '0',
      requires_preload: '0',
      requires_mfa: '0',
      is_business_bank: '0',
      ocr_supported: '0',
      type: 'bank',
      do_not_proxy: '0',
      updated_at: '2023-08-01 10:27:53',
      max_days: '365',
      get_address_supported: '0',
      supports_payment_summaries: '0',
      is_supported: '1',
      hide_merged_estatement_privacy_note: '0',
      time_next_stats_cron: '1690876808',
      time_next_session_cron: '1690857903',
      time_success_rate_updated: '1690851793',
      current_success_rate_ignore_abandoned: '0',
      current_success_rate_ignore_failed_login: '0',
      current_success_rate_all: '0',
      sessions_per_week: '0',
      time_next_outages_cron: '1690890642',
      icon: 'circle',
      iconColor: '#4caf50 !important',
    },
    {
      slug: 'aussieselect',
      name: 'Aussie Select',
      credentials: [
        {
          name: 'Customer number',
          fieldID: 'username',
          type: 'TEXT',
          description: '',
          validation: {
            minLength: 0,
            maxLength: 255,
            chars: '0-9',
          },
        },
        {
          name: 'Password',
          fieldID: 'password',
          type: 'password',
          description: '',
          values: '',
          validation: {
            minLength: 0,
            maxLength: 255,
            chars: '*',
          },
        },
      ],
      status: '',
      severity: '0',
      present: '1',
      available: '1',
      searchable: '1',
      display: '0',
      searchVal: 'aussieselect',
      region: 'au',
      export_with_password: '0',
      estatements_supported: '1',
      transaction_listings_supported: '1',
      card_validation_supported: '0',
      requires_preload: '0',
      requires_mfa: '0',
      is_business_bank: '0',
      ocr_supported: '0',
      type: 'bank',
      do_not_proxy: '0',
      updated_at: '2023-08-01 10:27:54',
      max_days: '364',
      get_address_supported: '0',
      supports_payment_summaries: '0',
      is_supported: '1',
      hide_merged_estatement_privacy_note: '0',
      time_next_stats_cron: '1690876808',
      time_next_session_cron: '1690857630',
      time_success_rate_updated: '1690851804',
      current_success_rate_ignore_abandoned: '0',
      current_success_rate_ignore_failed_login: '0',
      current_success_rate_all: '0',
      sessions_per_week: '0',
      time_next_outages_cron: '1690891678',
      icon: 'circle',
      iconColor: '#4caf50 !important',
    },
    {
      slug: 'auswide',
      name: 'Auswide Bank',
      credentials: [
        {
          name: 'Client Number',
          fieldID: 'username',
          type: 'TEXT',
          description: '',
          validation: {
            minLength: 0,
            maxLength: 255,
            chars: '0-9',
          },
        },
        {
          name: 'Access Code',
          fieldID: 'password',
          type: 'password',
          description: '',
          values: '',
          validation: {
            minLength: 0,
            maxLength: 255,
            chars: '*',
          },
        },
      ],
      status: '',
      severity: '0',
      present: '1',
      available: '1',
      searchable: '1',
      display: '0',
      searchVal: 'auswidebankawbwidebayaustraliawba',
      region: 'au',
      export_with_password: '0',
      estatements_supported: '0',
      transaction_listings_supported: '0',
      card_validation_supported: '0',
      requires_preload: '0',
      requires_mfa: '0',
      is_business_bank: '0',
      ocr_supported: '0',
      type: 'bank',
      do_not_proxy: '1',
      updated_at: '2023-08-01 10:27:54',
      max_days: '365',
      get_address_supported: '0',
      supports_payment_summaries: '0',
      is_supported: '1',
      hide_merged_estatement_privacy_note: '0',
      time_next_stats_cron: '1690876808',
      time_next_session_cron: '1690857268',
      time_success_rate_updated: '1690851790',
      current_success_rate_ignore_abandoned: '0',
      current_success_rate_ignore_failed_login: '0',
      current_success_rate_all: '0',
      sessions_per_week: '0',
      time_next_outages_cron: '1690891443',
      icon: 'circle',
      iconColor: '#4caf50 !important',
    },
    {
      slug: 'bankaust',
      name: 'Bank Australia',
      credentials: [
        {
          name: 'Customer Number',
          fieldID: 'username',
          type: 'TEXT',
          description: '',
          values: '',
          validation: {
            minLength: 0,
            maxLength: 9999999,
            chars: '*',
          },
        },
        {
          name: 'Password',
          fieldID: 'password',
          type: 'password',
          description: '',
          values: '',
          validation: {
            minLength: 0,
            maxLength: 9999999,
            chars: '*',
          },
        },
      ],
      status: '',
      severity: '0',
      present: '1',
      available: '1',
      searchable: '1',
      display: '0',
      searchVal:
        'bankaustraliabankmeculimitedmembersandeducationcreditunionswanhillcreditunionshcu',
      region: 'au',
      export_with_password: '0',
      estatements_supported: '1',
      transaction_listings_supported: '1',
      card_validation_supported: '0',
      requires_preload: '0',
      requires_mfa: '0',
      is_business_bank: '0',
      ocr_supported: '0',
      type: 'bank',
      do_not_proxy: '0',
      updated_at: '2023-08-01 10:27:53',
      max_days: '365',
      get_address_supported: '0',
      supports_payment_summaries: '0',
      is_supported: '1',
      hide_merged_estatement_privacy_note: '0',
      time_next_stats_cron: '1690876808',
      time_next_session_cron: '1690857504',
      time_success_rate_updated: '1690851798',
      current_success_rate_ignore_abandoned: '0',
      current_success_rate_ignore_failed_login: '0',
      current_success_rate_all: '0',
      sessions_per_week: '0',
      time_next_outages_cron: '1690890856',
      icon: 'circle',
      iconColor: '#4caf50 !important',
    },
    {
      slug: 'bankfirst',
      name: 'Bank First',
      credentials: [
        {
          name: 'Member Number',
          fieldID: 'username',
          type: 'TEXT',
          description: '',
          values: '',
          validation: {
            minLength: 0,
            maxLength: 9999999,
            chars: '*',
          },
        },
        {
          name: 'Password',
          fieldID: 'password',
          type: 'password',
          description: '',
          values: '',
          validation: {
            minLength: 0,
            maxLength: 9999999,
            chars: '*',
          },
        },
      ],
      status: '',
      severity: '0',
      present: '1',
      available: '1',
      searchable: '1',
      display: '0',
      searchVal:
        'bankfirstvictoriateachersmutualbankvtmbvicteachersmutualbankvictorianteachersmutualbank',
      region: 'au',
      export_with_password: '0',
      estatements_supported: '1',
      transaction_listings_supported: '1',
      card_validation_supported: '0',
      requires_preload: '0',
      requires_mfa: '0',
      is_business_bank: '0',
      ocr_supported: '0',
      type: 'bank',
      do_not_proxy: '0',
      updated_at: '2023-08-01 10:27:53',
      max_days: '365',
      get_address_supported: '0',
      supports_payment_summaries: '0',
      is_supported: '1',
      hide_merged_estatement_privacy_note: '0',
      time_next_stats_cron: '1690876808',
      time_next_session_cron: '1690857846',
      time_success_rate_updated: '1690851800',
      current_success_rate_ignore_abandoned: '0',
      current_success_rate_ignore_failed_login: '0',
      current_success_rate_all: '0',
      sessions_per_week: '0',
      time_next_outages_cron: '1690889463',
      icon: 'circle',
      iconColor: '#4caf50 !important',
    },
    {
      slug: 'bankmecu',
      name: 'BankMeCU',
      credentials: [
        {
          name: 'Customer Number',
          fieldID: 'username',
          type: 'TEXT',
          description: '',
          values: '',
          validation: {
            minLength: 0,
            maxLength: 9999999,
            chars: '*',
          },
        },
        {
          name: 'Net code',
          fieldID: 'password',
          type: 'password',
          description: '',
          values: '',
          validation: {
            minLength: 0,
            maxLength: 9999999,
            chars: '*',
          },
        },
      ],
      status:
        'We are currently experiencing issues in retrieving data from this institution. If you experience any problems, please try again later.',
      severity: '0',
      present: '0',
      available: '1',
      searchable: '1',
      display: '0',
      searchVal:
        'bankmeculimitedmembersandeducationcreditunionswanhillcreditunionshcu',
      region: 'au',
      export_with_password: '0',
      estatements_supported: '1',
      transaction_listings_supported: '0',
      card_validation_supported: '0',
      requires_preload: '0',
      requires_mfa: '0',
      is_business_bank: '0',
      ocr_supported: '0',
      type: 'bank',
      do_not_proxy: '0',
      updated_at: '2023-08-01 10:27:53',
      max_days: '365',
      get_address_supported: '0',
      supports_payment_summaries: '0',
      is_supported: '1',
      hide_merged_estatement_privacy_note: '0',
      time_next_stats_cron: '1690876808',
      time_next_session_cron: '1690856797',
      time_success_rate_updated: '1690851794',
      current_success_rate_ignore_abandoned: '0',
      current_success_rate_ignore_failed_login: '0',
      current_success_rate_all: '0',
      sessions_per_week: '0',
      time_next_outages_cron: '1690889335',
      icon: 'circle',
      iconColor: '#fb8c00 !important',
    },
    {
      slug: 'banksa',
      name: 'BankSA',
      credentials: [
        {
          name: 'Card/Access Number',
          fieldID: 'username',
          type: 'TEXT',
          description: '',
          values: '',
          validation: {
            minLength: 0,
            maxLength: 19,
            chars: '0-9',
          },
          keyboardType: 'number',
        },
        {
          name: 'Security Number',
          fieldID: 'security-number',
          type: 'password',
          description: '',
          values: '',
          validation: {
            minLength: 0,
            maxLength: 6,
            chars: '0-9',
          },
          keyboardType: 'number',
        },
        {
          name: 'Internet Password',
          fieldID: 'password',
          type: 'password',
          description: '',
          values: '',
          validation: {
            minLength: 6,
            maxLength: 12,
            chars: '*',
          },
          keyboardType: 'default',
        },
        {
          name: 'Issue Number (Select 1 if unsure)',
          fieldID: 'issue-number',
          type: 'select',
          description: '',
          values: {
            1: 1,
            2: 2,
            3: 3,
            4: 4,
          },
          defaultKey: '1',
          validation: {
            minLength: 0,
            maxLength: 9999999,
            chars: '*',
          },
          optional: true,
        },
      ],
      status: '',
      severity: '0',
      present: '1',
      available: '1',
      searchable: '1',
      display: '0',
      searchVal: 'banksathebankofsouthaustralia',
      region: 'au',
      export_with_password: '0',
      estatements_supported: '1',
      transaction_listings_supported: '1',
      card_validation_supported: '1',
      requires_preload: '0',
      requires_mfa: '0',
      is_business_bank: '0',
      ocr_supported: '1',
      type: 'bank',
      do_not_proxy: '0',
      updated_at: '2023-08-01 10:27:53',
      max_days: '365',
      get_address_supported: '1',
      supports_payment_summaries: '0',
      is_supported: '1',
      hide_merged_estatement_privacy_note: '0',
      time_next_stats_cron: '1690876808',
      time_next_session_cron: '1690857559',
      time_success_rate_updated: '1690851786',
      current_success_rate_ignore_abandoned: '0',
      current_success_rate_ignore_failed_login: '0',
      current_success_rate_all: '0',
      sessions_per_week: '0',
      time_next_outages_cron: '1690887659',
      icon: 'circle',
      iconColor: '#4caf50 !important',
    },
    {
      slug: 'banksyd',
      name: 'Bank of Sydney',
      credentials: [
        {
          name: 'Username',
          fieldID: 'username',
          type: 'TEXT',
          description: '',
          values: '',
          validation: {
            minLength: 0,
            maxLength: 9999999,
            chars: '*',
          },
        },
        {
          name: 'Password',
          fieldID: 'password',
          type: 'password',
          description: '',
          values: '',
          validation: {
            minLength: 0,
            maxLength: 9999999,
            chars: '*',
          },
        },
      ],
      status: '',
      severity: '0',
      present: '1',
      available: '1',
      searchable: '1',
      display: '0',
      searchVal: 'bankofsydneybanksydexperiencethedifference',
      region: 'au',
      export_with_password: '0',
      estatements_supported: '1',
      transaction_listings_supported: '1',
      card_validation_supported: '0',
      requires_preload: '0',
      requires_mfa: '0',
      is_business_bank: '0',
      ocr_supported: '0',
      type: 'bank',
      do_not_proxy: '0',
      updated_at: '2023-08-01 10:27:54',
      max_days: '365',
      get_address_supported: '0',
      supports_payment_summaries: '0',
      is_supported: '1',
      hide_merged_estatement_privacy_note: '0',
      time_next_stats_cron: '1690862402',
      time_next_session_cron: '1690856877',
      time_success_rate_updated: '1690851798',
      current_success_rate_ignore_abandoned: '0',
      current_success_rate_ignore_failed_login: '0',
      current_success_rate_all: '0',
      sessions_per_week: '0',
      time_next_outages_cron: '1690889194',
      icon: 'circle',
      iconColor: '#4caf50 !important',
    },
    {
      slug: 'bankwest',
      name: 'Bankwest',
      credentials: [
        {
          name: 'Personal Access Number (PAN)',
          fieldID: 'username',
          type: 'TEXT',
          description: '',
          values: '',
          validation: {
            minLength: 0,
            maxLength: 8,
            chars: '0-9',
          },
          keyboardType: 'number',
        },
        {
          name: 'Password',
          fieldID: 'password',
          type: 'password',
          description: '',
          values: '',
          validation: {
            minLength: 0,
            maxLength: 16,
            chars: '*',
          },
          keyboardType: 'default',
        },
      ],
      status: '',
      severity: '0',
      present: '1',
      available: '1',
      searchable: '1',
      display: '1',
      searchVal: 'bankwestthebankofwesternaustralia',
      region: 'au',
      export_with_password: '0',
      estatements_supported: '1',
      transaction_listings_supported: '1',
      card_validation_supported: '1',
      requires_preload: '0',
      requires_mfa: '0',
      is_business_bank: '0',
      ocr_supported: '1',
      type: 'bank',
      do_not_proxy: '1',
      updated_at: '2023-08-01 10:27:53',
      max_days: '365',
      get_address_supported: '1',
      supports_payment_summaries: '0',
      is_supported: '1',
      hide_merged_estatement_privacy_note: '0',
      time_next_stats_cron: '1690876808',
      time_next_session_cron: '1690856783',
      time_success_rate_updated: '1690851786',
      current_success_rate_ignore_abandoned: '0',
      current_success_rate_ignore_failed_login: '0',
      current_success_rate_all: '0',
      sessions_per_week: '7',
      time_next_outages_cron: '1690889468',
      icon: 'circle',
      iconColor: '#4caf50 !important',
    },
    {
      slug: 'bankwestbb',
      name: 'Bankwest Business',
      credentials: [
        {
          name: 'Personal Access Number (PAN)',
          fieldID: 'username',
          type: 'TEXT',
          description: '',
          values: '',
          validation: {
            minLength: 0,
            maxLength: 8,
            chars: '0-9',
          },
          keyboardType: 'number',
        },
        {
          name: 'Secure Code',
          fieldID: 'password',
          type: 'password',
          description: '',
          values: '',
          validation: {
            minLength: 0,
            maxLength: 16,
            chars: '*',
          },
          keyboardType: 'default',
        },
      ],
      status: '',
      severity: '0',
      present: '1',
      available: '1',
      searchable: '1',
      display: '1',
      searchVal: 'bankwestbusinessthebankofwesternaustraliabusiness',
      region: 'au',
      export_with_password: '0',
      estatements_supported: '1',
      transaction_listings_supported: '1',
      card_validation_supported: '1',
      requires_preload: '0',
      requires_mfa: '0',
      is_business_bank: '0',
      ocr_supported: '1',
      type: 'bank',
      do_not_proxy: '1',
      updated_at: '2023-08-01 10:27:53',
      max_days: '365',
      get_address_supported: '1',
      supports_payment_summaries: '0',
      is_supported: '1',
      hide_merged_estatement_privacy_note: '0',
      time_next_stats_cron: '1690862402',
      time_next_session_cron: '1690857832',
      time_success_rate_updated: '1690851805',
      current_success_rate_ignore_abandoned: '0',
      current_success_rate_ignore_failed_login: '0',
      current_success_rate_all: '0',
      sessions_per_week: '7',
      time_next_outages_cron: '1690860773',
      icon: 'circle',
      iconColor: '#4caf50 !important',
    },
    {
      slug: 'bank_of_captcha',
      name: 'Bank of CAPTCHA',
      credentials: [
        {
          name: 'Username',
          fieldID: 'username',
          type: 'TEXT',
          description: '',
          values: '',
          validation: {
            minLength: 0,
            maxLength: 9999999,
            chars: '*',
          },
          keyboardType: 'default',
        },
        {
          name: 'Password',
          fieldID: 'password',
          type: 'password',
          description: '',
          values: '',
          validation: {
            minLength: 0,
            maxLength: 9999999,
            chars: '*',
          },
          keyboardType: 'default',
        },
        {
          name: 'Enter Text Shown',
          fieldID: 'captcha',
          type: 'captcha',
          description: '',
          values: '',
          validation: {
            minLength: 0,
            maxLength: 9999999,
            chars: '*',
          },
          keyboardType: 'default',
        },
      ],
      status:
        'We are currently experiencing issues in retrieving data from this institution. If you experience any problems, please try again later.',
      severity: '0',
      present: '0',
      available: '1',
      searchable: '1',
      display: '0',
      searchVal: 'bankofcaptchademotest',
      region: '',
      export_with_password: '0',
      estatements_supported: '0',
      transaction_listings_supported: '0',
      card_validation_supported: '0',
      requires_preload: '1',
      requires_mfa: '0',
      is_business_bank: '0',
      ocr_supported: '0',
      type: 'bank',
      do_not_proxy: '0',
      updated_at: '2023-08-01 10:27:53',
      max_days: '365',
      get_address_supported: '0',
      supports_payment_summaries: '0',
      is_supported: '1',
      hide_merged_estatement_privacy_note: '0',
      time_next_stats_cron: '1690862402',
      time_next_session_cron: '1690857196',
      time_success_rate_updated: '1690851790',
      current_success_rate_ignore_abandoned: '0',
      current_success_rate_ignore_failed_login: '0',
      current_success_rate_all: '0',
      sessions_per_week: '39',
      time_next_outages_cron: '1690889622',
      icon: 'circle',
      iconColor: '#fb8c00 !important',
    },
    {
      slug: 'bank_of_custom',
      name: 'Bank of Custom Data',
      credentials: [
        {
          name: 'Username',
          fieldID: 'username',
          type: 'TEXT',
          description: '',
          values: '',
          validation: {
            minLength: 0,
            maxLength: 9999999,
            chars: '*',
          },
          keyboardType: 'default',
        },
        {
          name: 'Password',
          fieldID: 'password',
          type: 'password',
          description: '',
          values: '',
          validation: {
            minLength: 0,
            maxLength: 9999999,
            chars: '*',
          },
          keyboardType: 'default',
        },
      ],
      status: '',
      severity: '0',
      present: '1',
      available: '1',
      searchable: '1',
      display: '0',
      searchVal: 'testbankofcustomdatademonstration',
      region: '',
      export_with_password: '0',
      estatements_supported: '0',
      transaction_listings_supported: '0',
      card_validation_supported: '0',
      requires_preload: '0',
      requires_mfa: '0',
      is_business_bank: '0',
      ocr_supported: '0',
      type: 'bank',
      do_not_proxy: '0',
      updated_at: '2023-08-01 10:27:53',
      max_days: '365',
      get_address_supported: '0',
      supports_payment_summaries: '0',
      is_supported: '1',
      hide_merged_estatement_privacy_note: '0',
      time_next_stats_cron: '1690862402',
      time_next_session_cron: '1690854453',
      time_success_rate_updated: '1690851783',
      current_success_rate_ignore_abandoned: '9630',
      current_success_rate_ignore_failed_login: '7124',
      current_success_rate_all: '6934',
      sessions_per_week: '2027',
      time_next_outages_cron: '1690854188',
      icon: 'circle',
      iconColor: '#4caf50 !important',
    },
  ],
};
