name: Release
on:
  push:
    branches:
      - d/PLAT-*
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    environment: photon-design-system
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'

      - name: Install dependencies
        run: npm ci --ignore-scripts

      - name: Log into aws
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_THEMES }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_THEMES }}
          aws-region: ap-southeast-2

      - name: Fetch themes files.
        run: aws s3 sync s3://figma-themes/figmaThemes/version/latest/ ./public/themes/

      - name: Build Library
        run: npm run build:figma

      - name: Release
        env:
          GH_TOKEN_RELEASE: ${{ secrets.GH_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
        run: npx semantic-release