name: Preview Build

on:
  pull_request:

jobs:
  release:
    name: Preview Build
    runs-on: ubuntu-latest
    environment: photon-design-system
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install dependencies
        run: |
          npm config set '//npm.fontawesome.com/:_authToken' "${{ secrets.FONTAWESOME_NPM_AUTH_TOKEN }}"
          npm config set legacy-peer-deps=true --location=project
          npm install

      - name: Log into aws for themes
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_THEMES }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_THEMES }}
          aws-region: ap-southeast-2
#
#      - name: Create themes folder
#        run: mkdir ./public/figmaThemes

      #- name: Create themes folder
        #run: mkdir ./public/cxThemes

#      - name: Fetch themes files.
        #run: ./scripts/gets3files.sh

      - name: Build Library
        run: npm run build:lib
        env:
#          STORYBOOK_THEME_URL: 'figmaThemes'
          #STORYBOOK_THEME_URL: 'cxThemes'


# Disabling AWS Storybook Instance build and deploy because we're having AWS cred issues
# and this isn't mission critical. SF

#      - name: Log into aws for build
#        uses: aws-actions/configure-aws-credentials@v1
#        with:
#          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_BUILD }}
#          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_BUILD }}
#          aws-region: ap-southeast-2
#
#      - name: push to s3
#        run: aws s3 sync storybook-static/ s3://${{ secrets.BUCKET_NAME }}/${{ github.event.pull_request.number }}-${{ github.run_number }} --delete
#
#      - name: Comment on pr
#        uses: ./.github/workflows/actions/comment-action
#        with:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#          BUCKET_NAME: ${{ secrets.BUCKET_NAME }}
#          BUILD_VERSION: ${{ github.event.pull_request.number }}-${{ github.run_number }}
