name: Preview Build
on:
  pull_request:
    branches:
      - d/PLAT-*
jobs:
  release:
    name: Preview Build
    runs-on: ubuntu-latest
    environment: photon-design-system
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'

      - name: Install dependencies
        run: npm ci --ignore-scripts

#      - name: Log into aws for themes
#        uses: aws-actions/configure-aws-credentials@v1
#        with:
#          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_THEMES }}
#          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_THEMES }}
#          aws-region: ap-southeast-2
#
#      - name: Create themes folder
#        run: mkdir ./public/figmaThemes
#
#      - name: Fetch themes files.
#        run: ./scripts/gets3files.sh
#
#      - name: Build Library
#        run: npm run build:figma
#        env:
#          STORYBOOK_THEME_URL: 'figmaThemes'

#      - name: Log into aws for build
#        uses: aws-actions/configure-aws-credentials@v1
#        with:
#          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_BUILD }}
#          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_BUILD }}
#          aws-region: ap-southeast-2
#
#      - name: push to s3
#        run: ./scripts/pushToS3.sh
#        env:
#          PR_NUMBER: ${{ github.event.pull_request.number }}

      - name: Comment on pr
        uses: ./.github/workflows/actions/comment-action
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
