name: Release
on:
  push:
    branches:
      - main
      - d/PLAT-64-semantic-version-release
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    environment: photon-design-system
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'

      - name: Install dependencies
        run: npm ci

      - name: Build Library
        run: npm run build:lib

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          SLACK_TOKEN: ${{ secrets.SLACK_RELEASE_BOT_TOKEN }}
        run: npx semantic-release